Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -11,7 +11,7 @@ jobs:
   build-and-scan:
     runs-on: ubuntu-latest
     env:
-      DOCKER_IMAGE: sudhsriv510/pythonapp
+      #DOCKER_IMAGE: sudhsriv510/pythonapp
       SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -20,6 +20,19 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
+
+      - name: Official SonarQube Scan
+        uses: SonarSource/sonarqube-scan-action@v3.0.0
+        with:
+          projectBaseDir: .
+          args: >
+            -Dsonar.projectKey=hackathon-proj -Dsonar.host.url=${{ env.SONAR_HOST_URL
+            }} -Dsonar.login=${{ env.SONAR_TOKEN }}
+            -Dsonar.working.directory=./.scannerwork
+      - name: Print SonarQube Logs
+        run: >
+          ls -al .scannerwork
+          cat .scannerwork/report-task.txt || echo "report-task.txt not found"
 
       - name: Login to Amazon ECR Public
         id: login-ecr-public
@@ -49,18 +62,7 @@ jobs:
        # run: |
         #  docker push $DOCKER_IMAGE:${{ github.sha }}
          # docker push $DOCKER_IMAGE:latest
-      - name: Official SonarQube Scan
-        uses: SonarSource/sonarqube-scan-action@v3.0.0
-        with:
-          projectBaseDir: .
-          args: >
-            -Dsonar.projectKey=hackathon-proj -Dsonar.host.url=${{ env.SONAR_HOST_URL
-            }} -Dsonar.login=${{ env.SONAR_TOKEN }}
-            -Dsonar.working.directory=./.scannerwork
-      - name: Print SonarQube Logs
-        run: >
-          ls -al .scannerwork
-          cat .scannerwork/report-task.txt || echo "report-task.txt not found"
+
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
